# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcon < Formula
  desc "Terminal UI for Google Cloud Platform"
  homepage "https://github.com/slayer/gcon"
  version "0.0.0-demos"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slayer/gcon/releases/download/v0.0.0-demos/gcon_0.0.0-demos_darwin_amd64.tar.gz"
      sha256 "7bcacb5b4abca4fca9f4dc1ec65a5911cc2a6bd9307cdd008d729361b86505bd"

      define_method(:install) do
        bin.install "gcon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slayer/gcon/releases/download/v0.0.0-demos/gcon_0.0.0-demos_darwin_arm64.tar.gz"
      sha256 "c669c77ce29a645640e48e31906c4a84d6147332e1c337bda6749f7bcde3b60b"

      define_method(:install) do
        bin.install "gcon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slayer/gcon/releases/download/v0.0.0-demos/gcon_0.0.0-demos_linux_amd64.tar.gz"
      sha256 "6446ae0c1df7354b081a67161ae9188557946e60a2b73b3385b34754358bcd02"
      define_method(:install) do
        bin.install "gcon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slayer/gcon/releases/download/v0.0.0-demos/gcon_0.0.0-demos_linux_arm64.tar.gz"
      sha256 "e2446f1cbd04467d95a0e08cd75f57160da8ed5c4b3cc5fef07762f884a91136"
      define_method(:install) do
        bin.install "gcon"
      end
    end
  end

  test do
    system bin/"gcon", "--version"
  end
end
