# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcon < Formula
  desc "Terminal UI for Google Cloud Platform"
  homepage "https://github.com/slayer/gcon"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slayer/gcon/releases/download/v0.12.0/gcon_0.12.0_darwin_amd64.tar.gz"
      sha256 "2c35265daccbc3e1267d8ffd2fea0bd0278364b96dc80b50916d005b19a0d5fe"

      define_method(:install) do
        bin.install "gcon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slayer/gcon/releases/download/v0.12.0/gcon_0.12.0_darwin_arm64.tar.gz"
      sha256 "70d7957c9676ec85c6ef3d667465a52ef1734cc9fd1eda4cd15e32c83dbc787a"

      define_method(:install) do
        bin.install "gcon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slayer/gcon/releases/download/v0.12.0/gcon_0.12.0_linux_amd64.tar.gz"
      sha256 "703080586d1042bbee9d0a21aaa8d5a29af9ca6114456cc2d28dd14180a0330a"
      define_method(:install) do
        bin.install "gcon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slayer/gcon/releases/download/v0.12.0/gcon_0.12.0_linux_arm64.tar.gz"
      sha256 "2c452f25e9a9bd6227ca2fc3053b31e6c2549d245a0e763043b6e38a84e13756"
      define_method(:install) do
        bin.install "gcon"
      end
    end
  end

  test do
    system bin/"gcon", "--version"
  end
end
