# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcon" do
  name "gcon"
  desc "Terminal UI for Google Cloud Platform"
  homepage "https://github.com/slayer/gcon"
  version "0.7.0-rc1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcon"

  on_macos do
    on_intel do
      url "https://github.com/slayer/gcon/releases/download/v#{version}/gcon_#{version}_darwin_amd64.tar.gz"
      sha256 "33682f33005a07a9c90bf62bfb454abbf2e8713e3b8546d4724df9e3f34c8516"
    end
    on_arm do
      url "https://github.com/slayer/gcon/releases/download/v#{version}/gcon_#{version}_darwin_arm64.tar.gz"
      sha256 "f50e40efa561012045ef36423453af53cd43498be67b7cb7fbc77e00a3a6e3ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slayer/gcon/releases/download/v#{version}/gcon_#{version}_linux_amd64.tar.gz"
      sha256 "c839c9c0b89386fb7bd24a943feddc4cbc8729307e41738472e1360220137383"
    end
    on_arm do
      url "https://github.com/slayer/gcon/releases/download/v#{version}/gcon_#{version}_linux_arm64.tar.gz"
      sha256 "bc5e20030f990eb9ecd7ea3f57244e40443d8430fa53ff163e049580718e4470"
    end
  end

  # No zap stanza required
end
